GET http://localhost:8080//api/parseLink
Content-Type: application/json

{
  "urlSeed" : "https://en.wikipedia.org/wiki/Elon_Musk",
  "maxLinks" : 120,
  "forCompare": ["Tesla","Reeve","Elon Mask","Elon Musk","Musk"]
}